### ISSUE TITLE
Is it possible to exclude some URLs from auth'ing?

### ISSUE THREAD

**Issue by pataquets** [movableink/doorman#49]
I need some webhooks to be reachable without hitting Doorman and would like to know if there is some sort of whitelist or similar mechanism.
TIA.

**Comment by mchesler** [comment]
Hi Alfonso, this is already supported via the `publicPaths` configuration option.  See https://github.com/movableink/doorman/blob/master/conf.example.js#L33

**Comment by pataquets** [comment]
:man_facepalming: I missed it completely (low on coffee), sorry @mchesler.
Thank you very much.

**Comment by mchesler** [comment]
No worries at all @pataquets
